title: He's Aaron / 是落拓呀
description: Write code. Enjoy life.

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/ycraaron
  - title: LinkedIn
    img: /assets/images/linkedin.png
    url: https://www.linkedin.com/in/craaronyang/
  - title: Zhihu
    img: /assets/images/zhihu.ico
    url: https://www.zhihu.com/people/yang-cheng-rui/posts
  - title: Bilibili
    img: /assets/images/bilibili.png
    url: https://space.bilibili.com/43276908
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:craaron102@gmail.com

avatar: /assets/images/avatar.png
introduction: >
  Hi, there! I am Aaron.<br/>
  可以叫我落拓。<br/>
  I write code, work out, shoot vlog, try to live the life to the fullest. <br/>
  热爱一切美好事物。 

working:
  title: Working Experience
  timeline:
    - date: Now
    - "Tiancai: Software Engineer"
    - date: 2018-10
    - "Ambi Labs: Backend Engineer"
    - date: 2017-10

education:
  title: Education Background
  timeline:
    - date: 2017-08
    - "The University of Hong Kong, Master of Science In Computer science"
    - date: 2015-06
    - "WuHan University, Bachelor of Engineer in Software Engineering"
    - date: 2011-09

google_analytics: UA-45256157-13
