title: Aaron Yang / 是落拓呀
description: Write code. Enjoy life.

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/ycraaron
  - title: V2EX
    img: /assets/images/v2ex.png
    url: https://www.v2ex.com/member/heisaaron?r=heisaaron
  - title: Zhihu
    img: /assets/images/zhihu.png
    url: https://www.zhihu.com/people/yang-cheng-rui/posts
  - title: Bilibili
    img: /assets/images/bilibili.png
    url: https://space.bilibili.com/43276908
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:craaron102@gmail.com

avatar: /assets/images/avatar.png
introduction: >
  Hi! My nickname is xcatliu.<br/>
  中文昵称是流浪小猫，也可以叫我小猫。<br/>
  Whenever you see this lovely cat, yeah that’s me!

projects:
  title: Open Source Projects
  github:
    - xcatliu/mobi.css
    - xcatliu/typescript-tutorial
    - xcatliu/react-ie8
    - xcatliu/jekyllcn
    - xcatliu/leetcode
  content: >
    <p>Other projects that I have contributed can be found in <a href="https://github.com/xcatliu">github.com/xcatliu</a>.</p>
    <p>If you love my projects, please <a href="https://github.com/xcatliu/buy-me-a-coffee">buy me a coffee</a> to support me.</p>

working:
  title: Working Experience
  timeline:
    - date: Now
    - "Microsoft: Software Engineer II"
    - date: 2016-04
    - "Meituan: Senior Front-End Engineer"
    - date: 2015-04
    - "Meituan: Front-End Engineer"
    - date: 2013-06
    - "Meituan: Front-End Engineer Internship"
    - date: 2012-10

education:
  title: Education Background
  timeline:
    - date: 2013-06
    - "Bachelor of WuHan University: Computer Science and Technology"
    - date: 2009-09

google_analytics: UA-45256157-13
